apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-02-17T13:56:51Z"
  labels:
    kubernetes.io/metadata.name: argocd
  name: argocd
  resourceVersion: "6449"
  uid: fa7d6ac8-55a2-4aa8-8a90-23b971c0824e
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
